### ISSUE TITLE
Add 1366x768 edid

### ISSUE THREAD

**Issue by jpyper** [mdrjr/5422_bootini#1]
I know it's not hard to manually edit the boot.ini file, but a lot of older screens have a native resolution of 1366x768. I'm finding this in some TVs and generic LCD panels. I've also found that various Linux distros won't give 1366x768 as a display resolution without editing and enabling this in the boot.ini prior.

If you feel this doesn't help any, just close this issue. Thank you.

**Comment by mdrjr** [comment]
I quite didn't understood actually..

You don't want to edit boot.ini is that it? or you want a 1366x768 option on boot.ini ?

**Comment by jpyper** [comment]
Option added in the boot.ini would be nice. I'm not afraid to edit the boot.ini file myself, but others might be a little weary when messing with things they don't understand. Yeah, I'm sure it could be chalked up to laziness on my part though.

**Comment by mdrjr** [comment]
Can you tell me what you added to boot.ini that made it work?

**Comment by jpyper** [comment]
I'll have to get back to you tomorrow about it. I'm not at home for the rest of the night. I've starred the email for follow-up.

**Comment by jpyper** [comment]
Sorry for not continuing with this. I have moved 2 different times since my last post, and a lot of my gadgets were either sold or donated. I'm going to close this, and maybe revisit it someday in the future.
